version: "3.3"

services:
  crawler:
    container_name: tracking-crawler
    build:
      context: ./
      dockerfile: ./Dockerfile
    working_dir: /crawler
    restart: unless-stopped
    tty: true
    volumes:
      - .:/crawler
    networks:
      - tracking-network
    ports:
      - 9600:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      S3_UPLOAD_ACCESS_KEY_ID: ${S3_UPLOAD_ACCESS_KEY_ID}
      S3_UPLOAD_SECRET_ACCESS_KEY: ${S3_UPLOAD_SECRET_ACCESS_KEY}
      GCS_SERVICE_ACCOUNT_PATH: ${GCS_SERVICE_ACCOUNT_PATH}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      UPLOAD_BUCKET_NAME: ${UPLOAD_BUCKET_NAME}
      UPLOAD_REGION: ${UPLOAD_REGION}
      S3CLOUDFRONT: ${S3CLOUDFRONT}
      PORT: ${PORT}

networks:
  tracking-network:
